/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as shoeRegistryTestSol from "./ShoeRegistry.test.sol";
export type { shoeRegistryTestSol };
export type { Lock } from "./Lock";
