/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as shoeRegistryTestSol from "./ShoeRegistry.test.sol";
export { Lock__factory } from "./Lock__factory";
